Improve customization of outputs.
open62541/nodesetLoader pull request #197
Opened 2022-10-03 11:13 UTC by MurzynJ

Allow to select if stdout backend and examples for any backend are built.

2022-10-07 11:16 UTC, keba-uso requested changes
Hi. I was assigned to review your open PRs within the nodesetLoader repository, so we could speed up the merge process.

I've discussed with @andreasebner, and from now on each new commit within the nodesetLoader should include the same commit convention as on the open62541 repository.

Please change commit title to be compatible with the commit convention, for example:

- build(pack): Improve customization of outputs

2022-10-07 11:16 UTC, keba-uso commented on CMakeLists.txt
> +option(NL_BUILD_EXAMPLES "build examples" on)
Please change the newly added option to _ENABLE_EXAMPLES_, to preserve the overall structure. Also, the examples should be disabled by default:
`option(ENABLE_EXAMPLES "enable examples" off)`

2022-10-07 11:19 UTC, keba-uso commented
Also, please add the PR number in the commit message header: (#197)

2022-10-10 05:14 UTC, MurzynJ commented on CMakeLists.txt
> +option(NL_BUILD_EXAMPLES "build examples" on)
Good point about the name. Will be changed.
Changing the default to "off" breaks the current behaviour, which is to always build the examples. But I guess this is what we want. I will change is as you suggested.

2022-10-10 06:49 UTC, keba-uso commented on CMakeLists.txt
> +option(NL_BUILD_EXAMPLES "build examples" on)
Makes sense to keep both stdout and examples ON. Nice!

2022-10-12 13:40 UTC, merged